version: '3.7'
services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks: 
      - ml_platform

  postgres:
    image: postgres:10.5
    env_file:
      - scheduler/config/common.env
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U airflow" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks: 
      - ml_platform

  airflow-webserver:
    build: 
      context: ./scheduler
    restart: always
    command: webserver
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8080:8080"
    volumes:
      - ../ml_platform_dags/projects:/root/airflow/ext_dags
      - "/var/run/docker.sock:/var/run/docker.sock"
    env_file: 
      - scheduler/config/common.env
    healthcheck:
      test: [ "CMD-SHELL", "[ -f /airflow/airflow-webserver.pid ]" ]
      interval: 30s
      timeout: 30s
      retries: 3
    networks: 
      - ml_platform

  airflow-worker-1:
    build: 
      context: ./scheduler
    command: worker
    restart: always
    depends_on:
      - airflow-webserver
    ports:
      - "8081:8080"
    volumes:
      - ../ml_platform_dags/projects:/root/airflow/ext_dags
      - "/var/run/docker.sock:/var/run/docker.sock"
    env_file: 
      - scheduler/config/common.env
    environment:
      - QUEUE_NAME=queue_1
    networks: 
      - ml_platform

  airflow-worker-2:
    build: 
      context: ./scheduler
    command: worker
    restart: always
    depends_on:
      - airflow-webserver
    ports:
      - "8082:8080"
    volumes:
      - ../ml_platform_dags/projects:/root/airflow/ext_dags
      - "/var/run/docker.sock:/var/run/docker.sock"
    env_file: 
      - scheduler/config/common.env
    environment:
      - QUEUE_NAME=queue_2
    networks: 
      - ml_platform

  airflow-flower:
    build: 
      context: ./scheduler
    command: flower
    restart: always
    depends_on:
      - airflow-worker-1
      - airflow-worker-2
    ports:
      - "5555:5555"
    volumes:
      - ../ml_platform_dags/projects:/root/airflow/ext_dags
      - "/var/run/docker.sock:/var/run/docker.sock"
    env_file: 
      - scheduler/config/common.env
    networks: 
      - ml_platform

networks:
  ml_platform:
    external: true